### Instalación CDH5 & Hadoop en Ubuntu 12.04 ###
---
- name: Instalación OpenJDK, CDH5 y Hadoop
  hosts: vagrant
  remote_user: vagrant
  become: yes
  tasks:
  - name: Descargar OpenJDK-7
    apt:
      name: 
        - openjdk-7-jre
        - openjdk-7-jdk
      force_apt_get: yes

  - name: Descargar e instalar el paquete CDH5
    apt:
      deb: http://archive.cloudera.com/cdh5/one-click-install/precise/amd64/cdh5-repository_1.0_all.deb

  - name: Actualiazar con apt-get update
    apt:
      update_cache: yes

  - name: Instalar Hadoop
    apt:
      name: hadoop-0.20-conf-pseudo
      force_apt_get: yes
  
  - name: Verificar instalación Hadoop
    command: dpkg -L hadoop-0.20-conf-pseudo

  # Configuración Hadoop
  - name: Formatear el sistema de archivos
    command: sudo -u hdfs hdfs namenode -format -force

  - name: Arrancar los servicios HDFS
    shell: "for x in `cd /etc/init.d ; ls hadoop-hdfs-*` ; do sudo service $x start ; done"

  # Llegados a este punto, nos vamos a 192.168.100.100:50070 para verificar la instalación

...