---
- hosts: vagrant
  remote_user: vagrant
  become: yes
  tasks:
  - name: Download OpenJDK
    apt:
      name: 
        - openjdk-7-jre
        - openjdk-7-jdk
      force_apt_get: yes

  - name: Download and Install CDH 5 package
    apt:
      deb: http://archive.cloudera.com/cdh5/one-click-install/precise/amd64/cdh5-repository_1.0_all.deb

  - name: Update apt-get
    apt:
      update_cache: yes

  - name: Install Hadoop
    apt:
      name: hadoop-0.20-conf-pseudo
      force_apt_get: yes
  
  - name: Comprobación instalación Hadoop
    command: dpkg -L hadoop-0.20-conf-pseudo

  # Configuración Hadoop
  - name: Paso 1 - Formatear el NameNode
    command: sudo -u hdfs hdfs namenode -format -force

  - name: Paso 2 - Arrancar los servicios HDFS
    shell: "for x in `cd /etc/init.d ; ls hadoop-hdfs-*` ; do sudo service $x start ; done"

...
